// Generated by CoffeeScript 1.9.3
(function() {
  var app, cp, fs, io, runscript, sendfile, server;

  app = require('express')();

  server = require('http').Server(app);

  io = require('socket.io')(server);

  cp = require('child_process');

  server.listen(8080);

  app.get('/', function(req, res) {
    return res.sendfile(__dirname + '/web/' + '/index.html');
  });

  app.get(/(?:js|css|showdown)/, function(req, res) {
    return res.sendfile(__dirname + '/web/' + req.path);
  });

  app.get(/data/, function(req, res) {
    return res.sendfile(__dirname + req.path);
  });

  runscript = function(cmd, socket) {
    var run;
    console.log(cmd);
    run = cp.exec(cmd, {});
    socket.emit("log", "CMD start " + cmd);
    run.stdout.on('data', function(data) {
      return socket.emit("log", data);
    });
    run.stderr.on('data', function(data) {
      return socket.emit('err', data);
    });
    return run.on('exit', function() {
      return socket.emit("log", "CMD " + cmd + " finish");
    });
  };

  fs = require('fs');

  sendfile = function(file) {
    var str;
    str = fs.readFileSync(file, 'utf-8');
    return str;
  };

  io.on('connection', function(socket) {
    socket.emit('log', 'successfully connect');
    socket.on('runscript', function(data) {
      return runscript(data, socket);
    });
    return socket.on('needfile', function(data) {
      var resp;
      resp = {
        name: data['filename'],
        type: data['type'],
        container: data["container"],
        content: sendfile(data['filename'])
      };
      return socket.emit("file", resp);
    });
  });

}).call(this);
